In [84]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot  as plt
import pandas as pd

In [85]:
tf.__version__

'2.2.0'

In [86]:
dataset.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [87]:
dataset.shape

(10000, 14)

In [88]:
# Checking null values
dataset.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [89]:
# Seperating Dependent and Independent Dataset 

dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.drop(['RowNumber','CustomerId','Surname','Exited'],axis=1)
y = dataset['Exited']
X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [90]:
# Dummy encoding for Categorical COlumns
X = pd.get_dummies(X,columns=['Geography','Gender'],drop_first=True)

In [91]:
# Splitting Data into training Data and test set

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size= 0.2,random_state =0)

In [92]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

### Building ANN

In [93]:
# Initializing the ANN
ann = tf.keras.models.Sequential()

In [94]:
# Bilding the input Layer and 1st Hidden Layer

ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [95]:
# Bilding the 2nd Hidden Layer

ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [96]:
# Building Outpt layer

ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

### Compiling The ANN

In [97]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics = ['accuracy'])

In [98]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5567 - accuracy: 0.7832
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4793 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4544 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4399 - accuracy: 0.7965
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4291 - accuracy: 0.8065
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4208 - accuracy: 0.8173
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4093 - accuracy: 0.8270
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3948 - accuracy: 0.8380
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3818 - accuracy: 0.8450
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3718 - accuracy: 0.8510
Epoch 11/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3640 - accuracy: 0.8539
Epoch 12/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3584 - accuracy: 0.8572
Epoch 13/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3539 - accuracy: 0.8570
Epoch 14/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3511 - accuracy: 0.8580
Epoch 15/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3487 - accuracy: 0.8569
Epoch 16/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3469 - accuracy: 0.8581
Epoch 17/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3455 - accuracy: 0.8579
Epoch 18/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3445 - accuracy: 0.8590
Epoch 19/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3435 - accuracy: 0.8583
Epoch 20/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3424 - accuracy: 0.8590
Epoch 21/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3418 - accuracy: 0.8605
Epoch 22/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3410 - accuracy: 0.8609
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3409 - accuracy: 0.8595
Epoch 24/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3399 - accuracy: 0.8608
Epoch 25/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3400 - accuracy: 0.8600
Epoch 26/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3394 - accuracy: 0.8622
Epoch 27/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3389 - accuracy: 0.8616
Epoch 28/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3385 - accuracy: 0.8629
Epoch 29/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3383 - accuracy: 0.8624
Epoch 30/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3380 - accuracy: 0.8626
Epoch 31/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3376 - accuracy: 0.8633
Epoch 32/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3373 - accuracy: 0.8641
Epoch 33/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3371 - accuracy: 0.8637
Epoch 34/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3370 - accuracy: 0.8640
Epoch 35/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3367 - accuracy: 0.8625
Epoch 36/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3366 - accuracy: 0.8634
Epoch 37/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3363 - accuracy: 0.8637
Epoch 38/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3359 - accuracy: 0.8643
Epoch 39/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3361 - accuracy: 0.8639
Epoch 40/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3358 - accuracy: 0.8649
Epoch 41/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3356 - accuracy: 0.8644
Epoch 42/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3356 - accuracy: 0.8637
Epoch 43/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3355 - accuracy: 0.8641
Epoch 44/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3353 - accuracy: 0.8648
Epoch 45/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3350 - accuracy: 0.8646
Epoch 46/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3352 - accuracy: 0.8626
Epoch 47/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3350 - accuracy: 0.8643
Epoch 48/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3347 - accuracy: 0.8644
Epoch 49/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3347 - accuracy: 0.8656
Epoch 50/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3346 - accuracy: 0.8641
Epoch 51/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3344 - accuracy: 0.8634
Epoch 52/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3346 - accuracy: 0.8646
Epoch 53/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3340 - accuracy: 0.8648
Epoch 54/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3344 - accuracy: 0.8645
Epoch 55/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3342 - accuracy: 0.8646
Epoch 56/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3340 - accuracy: 0.8643
Epoch 57/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3345 - accuracy: 0.8630: 0s - loss: 0.3434 - accura
Epoch 58/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3337 - accuracy: 0.8652
Epoch 59/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3342 - accuracy: 0.8641
Epoch 60/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3339 - accuracy: 0.8644
Epoch 61/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3336 - accuracy: 0.8655
Epoch 62/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3339 - accuracy: 0.8646
Epoch 63/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3334 - accuracy: 0.8651
Epoch 64/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3336 - accuracy: 0.8627
Epoch 65/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3332 - accuracy: 0.8652
Epoch 66/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3337 - accuracy: 0.8635
Epoch 67/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3334 - accuracy: 0.8651
Epoch 68/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3335 - accuracy: 0.8652
Epoch 69/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3331 - accuracy: 0.8640
Epoch 70/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3334 - accuracy: 0.8639
Epoch 71/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3333 - accuracy: 0.8648
Epoch 72/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3333 - accuracy: 0.8645
Epoch 73/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3330 - accuracy: 0.8644
Epoch 74/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3333 - accuracy: 0.8656
Epoch 75/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3333 - accuracy: 0.8641
Epoch 76/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3333 - accuracy: 0.8640
Epoch 77/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3333 - accuracy: 0.8636
Epoch 78/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3329 - accuracy: 0.8641
Epoch 79/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3327 - accuracy: 0.8651
Epoch 80/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3329 - accuracy: 0.8646
Epoch 81/100

250/250 [==============================] - 0s 2ms/step - loss: 0.3330 - accuracy: 0.8651
Epoch 82/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3328 - accuracy: 0.8644
Epoch 83/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3331 - accuracy: 0.8656
Epoch 84/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3327 - accuracy: 0.8650
Epoch 85/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3328 - accuracy: 0.8660: 0s - loss: 0.3292 -
Epoch 86/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3328 - accuracy: 0.8640
Epoch 87/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3325 - accuracy: 0.8644
Epoch 88/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3326 - accuracy: 0.8652
Epoch 89/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3324 - accuracy: 0.8660
Epoch 90/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3324 - accuracy: 0.8654
Epoch 91/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3324 - accuracy: 0.8648
Epoch 92/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3324 - accuracy: 0.8651
Epoch 93/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3322 - accuracy: 0.8661
Epoch 94/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3325 - accuracy: 0.8651
Epoch 95/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3317 - accuracy: 0.8660
Epoch 96/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3324 - accuracy: 0.8643
Epoch 97/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3323 - accuracy: 0.8629
Epoch 98/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3322 - accuracy: 0.8645
Epoch 99/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3320 - accuracy: 0.8652
Epoch 100/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3322 - accuracy: 0.8641

### Predicting the Out put for Test set

In [110]:
y_pred = ann.predict(X_test)
Y_pred_c = y_pred.round()

### Calculating the Accuracy of ANN

In [111]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_pred_c,y_test)

0.8625